apiVersion: apps/v1
kind: Deployment
metadata:
  name: ma-db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maDb
  template:
    metadata:
      labels:
        app: maDb
    spec:
      containers:
      - name: my-container
        image: postgres:16 
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "100Mi" 
            cpu: "100m"      
          limits:
            memory: "200Mi"
            cpu: "200m"
        env:
        - name: POSTGRES_DB
          value: "voiture"
        - name: POSTGRES_USER
          value: "yahia"
        - name: POSTGRES_PASSWORD
          value: "yahia"
