apiVersion: apps/v1
kind: Deployment
metadata:
  name: voiture-dep
  labels:
    app: voiture-dep
spec:
  replicas: 3 # 3 replicas of the pod
  selector:
    matchLabels:
      app: voiture-dep
  template:
    metadata:
      labels:
        app: voiture-dep
    spec:
      containers:
      - name: voiture-dep-container
        image: yzriga/voiture:v1
        env:
        - name: POSTGRES_DB
          value: "voiture"
        - name: POSTGRES_USER
          value: "yahia"
        - name: POSTGRES_PASSWORD
          value: "yahia"
        - name: RUNNING_CONTAINER
          value: "public"
        - name: POSTGRES_DB
          value: "voiture"
        - name: POSTGRES_USER
          value: "yahia"
        - name: POSTGRES_PASSWORD
          value: "yahia"
        - name: DATABASE_HOST
          value: "db"
        - name: DATABASE_PORT
          value: "5432"
        ports:
        - containerPort: 8080
