apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monDep
  template:
    metadata:
      labels:
        app: monDep
    spec:
      containers:
      - name: my-container
        image: xhelozs/csc8567:v1  
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "100Mi" 
            cpu: "100m"      
          limits:
            memory: "200Mi"
            cpu: "200m"